### ISSUE TITLE
Submit Classic Arcade Game Clone

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/FENDp3#1]
**_objective / purpose_**  
Complete P3 submission. Normally, I'd open issues to detail out the items on this epic checklist, but for now this epic checklist will serve as a catch-all for the rubric located [here](https://review.udacity.com/#!/rubrics/15/view).

**_completion checklist_**
- [x] Changes Listed  (mark each member as completed)
  - [x] Baseline commit from Udacity master  
  - [x] Configure for DevFlow and setup my standard labels  
  - [x] Create epic for ~20hr budget (this issue)
  - [x] (setup in progress) Track time to complete using Timely  
  - [x] Setup readme instructions for game siting source  
  - [x] Create a winner modal overaly
  - [x] Create psuedo code and initial classes
  - [x] Player navigation and movement
  - [x] Complete the player 'hero' navigation and movement
  - [x] Add enemies to the board
  - [x] Handle collisions
  - [x] At win, present modal
  - [x] Ensure game reset works  
- [x] Developer Tested - Test Copies (Disposable Alpha "DA!s" and Release Candidate)

POST LIVE:
- [x] Not required to work on mobile and tablets
- [x] Accepted by Udacity reviewer

**_full pipeline documentation_**
---
# Overview - describe with history and related items  
# Solution Design
## Project Specification - Classic Arcade Game Clone
From rubric, this serves as a checklist prior to testing and submission.
 - [x] Opening `index.html` should load the game  
 - [x] Error Free Game Functions: The game functions correctly and runs error free  
   - [x] Player can not move off screen
   - [x] Vehicles cross the screen
   - [x] Vehicle-player collisions happen logically (not too early or too late)
   - [x] Vehicle-player collision resets the game
   - [x] Something happens when player wins
 - [x] Object Oriented Code: Game objects (player and vehicles) are implemented using JavaScript object-oriented programming features
 - [x] Documentation
   - [x] README: A `README` file is included detailing all steps required to successfully run the application. How to load and play the game.
   - [x] Comments: Comments are present and effectively explain longer code procedures. As a rule of thumb: describe what all custom functions and object methods do.
   - [x] Code Quality: Code is formatted with consistent, logical, and easy-to-read formatting as described in the [Udacity JavaScript Style Guide](http://udacity.github.io/frontend-nanodegree-styleguide/javascript.html)
 - [x] Future nice to have functionaly not required 
   - [ ] Add collectible items on screen
   - [ ] Mulitple vehicle types
   - [ ] Timed games
   - [ ] Be creative!

# What's New Entry  
n/a
# Solution Implementation Notes  
## Customer Experience - Re-open and append if issues for customers
n/a

**Comment by rudimusmaximus** [comment]
# The instructions follow up
The instructions are detailed and include many links for further research.
Please review and document being sure to index in my notes.

 - [ ] diigo instructions and this epic note post completions
 - [ ] post graduation, add the additional functionality to practice more

For example, the `ctx` object is a CanvasRenderingContext2D object. [This documentation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D) provides all of the methods that are available to that object.

**Comment by rudimusmaximus** [comment]
![winner.gif](https://images.zenhubusercontent.com/59518c8261b4ca3b0a726039/c699679f-717c-4e51-bac5-5e50cebcb87d)
Source: https://blog.prizegrab.com/cooking-with-fire article
Use this for winner overlay modal
Use [THIS approach for ES6 JS modal](https://lowrey.me/modals-in-pure-es6-javascript/)
Site sources in code.

**Comment by rudimusmaximus** [comment]
Added winner image to resources image files.

**Comment by rudimusmaximus** [comment]
Logged 24 effort hours. Issues currently when submitting. Seeking help

**Comment by rudimusmaximus** [comment]
The requirement "Something happens when player wins" was met, but review wanted an auto reset on game win which is not required.
Reset only required for collision.
I did make the changes of adding strict to all js files and to specify language in html tag.
Second submission v1.0.1 sent with these comments.
